---
- import_tasks: Debian.yml
  when: ansible_os_family == 'Debian'
- import_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat'
- name: run bfgminer autogen
  become: no
  command: /bin/sh autogen.sh
  args:
    chdir: /usr/local/src/bfgminer
  environment:
    CFFLAGS: -02
- name: configure bfgminer
  become: no
  command: ./configure --enable-futurebit --enable-scrypt --disable-sha256d
  args:
    chdir: /usr/local/src/bfgminer
- name: make bfgminer
  become: no
  make:
    params:
      MAKEFLAGS: -j{{ compile_threads }}
      NUM_THREADS: "{{ compile_threads }}"
  args:
    chdir: /usr/local/src/bfgminer
- name: install bfgminer
  become: yes
  make:
    target: install
  args:
    chdir: /usr/local/src/bfgminer
- name: run ldconfig to fix stupid linking error that keep popping up
  become: yes
  command: ldconfig
- name: git reset bfgminer
  become: yes
  command:
  args:
    chdir: /usr/local/src/bfgminer
    argv:
      - git
      - reset
      - --hard
      - "{{ bfgminer_version }}"
- name: git clean bfgminer
  become: yes
  command:
  args:
    chdir: /usr/local/src/bfgminer
    argv:
      - git
      - clean
      - -xfd
- name: git clean bfgminer submodules
  become: yes
  shell: git submodule foreach --recursive git clean -xfd
  args:
    chdir: /usr/local/src/bfgminer