---
- name: install bfgminer dependencies
  become: yes
  apt:
    state: present
    name: [
      'libcurl4-gnutls-dev',
      'libjansson-dev',
      'libudev-dev',
      'libncurses5-dev',
      'libncursesw5-dev',
      'libmicrohttpd-dev',
      'libevent-dev',
      'uthash-dev',
    ]
  register: result
  retries: 3
  delay: 10
  until: not result.failed