---
# tasks file for pi_install_bfgminer
- name: install bfgminer dependencies
  apt:
    state: present
    name: [
      'libcurl4-gnutls-dev',
      'libjansson-dev',
      'libudev-dev',
      'libncurses5-dev',
      'libncursesw5-dev',
      'libmicrohttpd-dev',
      'libevent-dev',
      'uthash-dev',
    ]
  register: result
  retries: 3
  delay: 10
  until: not result.failed
- name: clone IRMooBear/bfgminer
  git:
    repo: https://github.com/IRMooBear/bfgminer.git
    dest: /usr/local/src/bfgminer
    clone: yes
    update: yes
    recursive: yes
    force: yes
    version: "{{ bfgminer_version }}"
  register: bfgminer_repo
  retries: 3
  delay: 10
  until: not bfgminer_repo.failed
- debug:
    var: bfgminer_repo
- name: set pi user as owner of bfgminer
  file:
    path: /usr/local/src/bfgminer
    owner: pi
    recurse: true
- name: run bfgminer autogen
  become: false
  command: /bin/sh autogen.sh
  args:
    chdir: /usr/local/src/bfgminer
  environment:
    CFFLAGS: -02
  when: bfgminer_repo.changed
- name: configure bfgminer
  become: false
  command: ./configure --enable-futurebit --enable-scrypt --disable-sha256d
  args:
    chdir: /usr/local/src/bfgminer
  when: bfgminer_repo.changed
- name: make bfgminer
  become: false
  make:
    params:
      NUM_THREADS: "{{ ansible_processor_cores }}"
  args:
    chdir: /usr/local/src/bfgminer
  when: bfgminer_repo.changed
- name: install bfgminer
  become: true
  make:
    target: install
  args:
    chdir: /usr/local/src/bfgminer
  when: bfgminer_repo.changed
- name: run ldconfig to fix stupid linking error that keep popping up
  command: ldconfig
  when: bfgminer_repo.changed
- name: git reset bfgminer
  command:
  args:
    chdir: /usr/local/src/bfgminer
    argv:
      - git
      - reset
      - --hard
      - "{{ bfgminer_version }}"
- name: git clean bfgminer
  command:
  args:
    chdir: /usr/local/src/bfgminer
    argv:
      - git
      - clean
      - -xfd
- name: git clean bfgminer submodules
  shell: git submodule foreach --recursive git clean -xfd
  args:
    chdir: /usr/local/src/bfgminer
- name: install bfgminer template
  template:
    src: bfgminer.conf.ini
    dest: /etc/bfgminer.conf
    mode: 0755
    backup: yes
- name: create bfgminer systemctl service
  template:
    src: bfgminer.service.ini
    dest: /lib/systemd/system/bfgminer.service
    mode: 0755
- name: reload systemd
  systemd:
    daemon_reload: yes
- name: auto start bfgminer
  systemd:
    name: bfgminer.service
    enabled: yes
  when: bfgminer_autostart