---
# tasks file for pi_install_bfgminer
- name: check bfgminer exists
  stat:
    path: /usr/local/bin/bfgminer
  register: bfgminer_check
- name: clone IRMooBear/bfgminer
  git:
    repo: https://github.com/IRMooBear/bfgminer.git
    dest: /usr/local/src/bfgminer
    clone: yes
    update: yes
    recursive: yes
    force: yes
    version: "{{ bfgminer_version }}"
  register: bfgminer_repo
  retries: 3
  delay: 10
  until: not bfgminer_repo.failed
- name: set user as owner of bfgminer
  file:
    path: /usr/local/src/bfgminer
    owner: "{{ ansible_user }}"
    recurse: true
- import_tasks: compile_bfgminer.yml
  when: not bfgminer_check.stat.exists or bfgminer_repo.before != bfgminer_repo.after
- name: create bfgminer systemctl service
  template:
    src: bfgminer.service.ini
    dest: /lib/systemd/system/bfgminer.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart bfgminer
- name: install bfgminer template
  template:
    src: bfgminer.conf.ini
    dest: /etc/bfgminer.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart bfgminer
- name: auto start bfgminer
  systemd:
    name: bfgminer.service
    enabled: "{{ bfgminer_autostart }}"
  notify:
    - restart bfgminer